import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import { z } from "zod";
import { db } from "@/lib/db";
import { resetTokens, users } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { isRateLimited, getClientIp } from "@/lib/rate-limit";
import { logger } from "@/lib/logger";

const resetPasswordSchema = z.object({
  // Tokens generated by forgot-password are 32-byte hex strings (64 chars)
  token: z.string().min(32).max(256),
  password: z.string().min(8, "Password must be at least 8 characters").max(200),
});

export async function POST(request: Request) {
  // Rate limit: 5 attempts per 15 minutes per IP
  const ip = getClientIp(request);
  if (isRateLimited(ip, 5, 15 * 60 * 1000)) {
    return NextResponse.json(
      { error: "Too many attempts. Please try again later." },
      { status: 429 }
    );
  }

  try {
    const body = await request.json().catch(() => null);
    const parsed = resetPasswordSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0]?.message ?? "Invalid request." },
        { status: 400 }
      );
    }
    const { token, password } = parsed.data;

    // Reset tokens are stored by SHA-256 hash, so a DB read leak can't
    // be used to reset passwords. Hash the incoming raw token and look
    // up by the hash.
    const tokenHash = crypto.createHash("sha256").update(token).digest("hex");
    const [tokenData] = await db
      .select()
      .from(resetTokens)
      .where(eq(resetTokens.token, tokenHash))
      .limit(1);

    if (!tokenData) {
      return NextResponse.json(
        { error: "Invalid or expired reset link. Please request a new one." },
        { status: 400 }
      );
    }

    if (tokenData.usedAt || new Date(tokenData.expiresAt) < new Date()) {
      return NextResponse.json(
        { error: "This reset link has expired. Please request a new one." },
        { status: 400 }
      );
    }

    // Hash the new password
    const newHash = await bcrypt.hash(password, 12);

    // Check if this is the env-var admin or a DB user
    const adminEmail = process.env.ADMIN_EMAIL;
    const isEnvAdmin = adminEmail && tokenData.email.toLowerCase() === adminEmail.toLowerCase();

    if (isEnvAdmin) {
      // For env-var admin: upsert a DB user record with the new password
      // Auth checks DB users first, so this will take precedence over the env hash
      const [existing] = await db
        .select()
        .from(users)
        .where(eq(users.email, tokenData.email))
        .limit(1);

      if (existing) {
        await db
          .update(users)
          .set({ passwordHash: newHash, updatedAt: new Date().toISOString() })
          .where(eq(users.id, existing.id));
      } else {
        await db.insert(users).values({
          email: tokenData.email,
          name: "Admin",
          passwordHash: newHash,
          role: "admin",
        });
      }
    } else {
      // For regular DB users
      const [user] = await db
        .select()
        .from(users)
        .where(eq(users.email, tokenData.email))
        .limit(1);

      if (!user) {
        return NextResponse.json(
          { error: "User not found." },
          { status: 404 }
        );
      }

      await db
        .update(users)
        .set({ passwordHash: newHash, updatedAt: new Date().toISOString() })
        .where(eq(users.id, user.id));
    }

    // Mark token as used
    await db
      .update(resetTokens)
      .set({ usedAt: new Date().toISOString() })
      .where(eq(resetTokens.id, tokenData.id));

    return NextResponse.json({
      success: true,
      message: "Password updated successfully. You can now sign in.",
    });
  } catch (error) {
    logger.error("Reset password error", { error: String(error) });
    return NextResponse.json(
      { error: "Something went wrong. Please try again." },
      { status: 500 }
    );
  }
}
